### ISSUE TITLE
How to set the value of pair_style mtd?

### ISSUE THREAD

**Issue by AlexanderOnly** [MDIL-SNU/G-metaD#2]
I was wondering what these parameters mean, and how to set:

> pair_style mtd 1e-4 1 &
>                Si 0.001 1.0 20 &
>                1 &
>                1.0

Thanks

**Comment by JisuJung928** [comment]
Hello, AlexanderOnly.

I update the README that can answer your question.
These parameters are condition number, the number of elements, symbol, height, and width of bias potential, update interval, the number of types, and coefficient of bias potential.

Please read our [paper](https://doi.org/10.1038/s41524-021-00595-5) that describes how to set the parameters.

Best regards,
Jisu

**Comment by AlexanderOnly** [comment]
> Hello, AlexanderOnly.
> 
> I update the README that can answer your question. These parameters are condition number, the number of elements, symbol, height, and width of bias potential, update interval, the number of types, and coefficient of bias potential.
> 
> Please read our [paper](https://doi.org/10.1038/s41524-021-00595-5) that describes how to set the parameters.
> 
> Best regards, Jisu

Thank you for your reply! 
Another question is how to set the "potential_saved" file for multinary (binary or higher) compounds? Can I write like this:
`ELEM_LIST Ca O

POT Ca 6.0
SYM 26
2 6.0 0.003214 0.0 0.0 Ca
2 6.0 0.035711 0.0 0.0 Ca
2 6.0 0.071421 0.0 0.0 Ca
2 6.0 0.124987 0.0 0.0 Ca
2 6.0 0.214264 0.0 0.0 Ca
2 6.0 0.357106 0.0 0.0 Ca
2 6.0 0.714213 0.0 0.0 Ca
2 6.0 1.428426 0.0 0.0 Ca
4 6.0 0.000357 1.0 -1.0 Ca Ca
4 6.0 0.028569 1.0 -1.0 Ca Ca
4 6.0 0.089277 1.0 -1.0 Ca Ca
4 6.0 0.000357 2.0 -1.0 Ca Ca
4 6.0 0.028569 2.0 -1.0 Ca Ca
4 6.0 0.089277 2.0 -1.0 Ca Ca
4 6.0 0.000357 4.0 -1.0 Ca Ca
4 6.0 0.028569 4.0 -1.0 Ca Ca
4 6.0 0.089277 4.0 -1.0 Ca Ca
4 6.0 0.000357 1.0 1.0 Ca Ca
4 6.0 0.028569 1.0 1.0 Ca Ca
4 6.0 0.089277 1.0 1.0 Ca Ca
4 6.0 0.000357 2.0 1.0 Ca Ca
4 6.0 0.028569 2.0 1.0 Ca Ca
4 6.0 0.089277 2.0 1.0 Ca Ca
4 6.0 0.000357 4.0 1.0 Ca Ca
4 6.0 0.028569 4.0 1.0 Ca Ca
4 6.0 0.089277 4.0 1.0 Ca Ca

POT O 6.0
SYM 26
2 6.0 0.003214 0.0 0.0 O
2 6.0 0.035711 0.0 0.0 O
2 6.0 0.071421 0.0 0.0 O
2 6.0 0.124987 0.0 0.0 O
2 6.0 0.214264 0.0 0.0 O
2 6.0 0.357106 0.0 0.0 O
2 6.0 0.714213 0.0 0.0 O
2 6.0 1.428426 0.0 0.0 O
4 6.0 0.000357 1.0 -1.0 O O
4 6.0 0.028569 1.0 -1.0 O O
4 6.0 0.089277 1.0 -1.0 O O
4 6.0 0.000357 2.0 -1.0 O O
4 6.0 0.028569 2.0 -1.0 O O
4 6.0 0.089277 2.0 -1.0 O O
4 6.0 0.000357 4.0 -1.0 O O
4 6.0 0.028569 4.0 -1.0 O O
4 6.0 0.089277 4.0 -1.0 O O
4 6.0 0.000357 1.0 1.0 O O
4 6.0 0.028569 1.0 1.0 O O
4 6.0 0.089277 1.0 1.0 O O
4 6.0 0.000357 2.0 1.0 O O
4 6.0 0.028569 2.0 1.0 O O
4 6.0 0.089277 2.0 1.0 O O
4 6.0 0.000357 4.0 1.0 O O
4 6.0 0.028569 4.0 1.0 O O
4 6.0 0.089277 4.0 1.0 O O
`

**Comment by JisuJung928** [comment]
Yes, that's right.

The `potential_saved` you wrote will work!
If you want to know more about the format of `potential_saved`, our code [SIMPLE-NN](https://github.com/MDIL-SNU/SIMPLE-NN_v2) would be helpful.

Best regards,
Jisu
